ARG IMAGE_NAME=dustynv/ros:eloquent-ros-base-l4t-r32.7.1
FROM ${IMAGE_NAME}
ARG ZED_SDK_MAJOR=3
ARG ZED_SDK_MINOR=7
ARG ZED_SDK_PATCH=7
ARG L4T_MAJOR=32
ARG L4T_MINOR=7

ENV DEBIAN_FRONTEND noninteractive

# Disable apt-get warnings
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 42D5A192B819C5DA || true && \
  apt-get update || true && apt-get install -y --no-install-recommends apt-utils dialog && \
  rm -rf /var/lib/apt/lists/*

ENV TZ=Europe/Paris

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \ 
  apt-get update && \
  apt-get install --yes lsb-release wget less udev sudo build-essential cmake python3 python3-dev python3-pip python3-wheel git jq libpq-dev zstd usbutils && \    
  rm -rf /var/lib/apt/lists/*

# Install Python 3.7 and additional dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    apt-utils dialog \
    python3.7 python3.7-dev python3.7-distutils \
    build-essential cmake python3-pip python3-wheel git jq libpq-dev zstd usbutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Update pip and setuptools
RUN python3 -m pip install --upgrade pip setuptools

# Install Cython and NumPy
RUN pip3 install cython==0.28
RUN pip3 install numpy==1.13

# Set up ZED SDK
RUN apt-get update -y || true && \
    apt-get install -y --no-install-recommends \
    zstd wget less cmake curl gnupg2 \
    build-essential python3 python3-pip python3-dev python3-setuptools libusb-1.0-0-dev && \
    pip install protobuf && \
    wget -q --no-check-certificate -O ZED_SDK_Linux_JP.run \
    https://download.stereolabs.com/zedsdk/${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}/l4t${L4T_MAJOR}.${L4T_MINOR}/jetsons && \
    chmod +x ZED_SDK_Linux_JP.run && \
    ./ZED_SDK_Linux_JP.run silent drivers && \
    rm -rf /usr/local/zed/resources/* && \
    rm -rf ZED_SDK_Linux_JP.run && \
    rm -rf /var/lib/apt/lists/*

#This symbolic link is needed to use the streaming features on Jetson inside a container
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0 /usr/lib/aarch64-linux-gnu/libv4l2.so

# Clone ZED Python API repository
WORKDIR /usr/local/zed
RUN git clone https://github.com/stereolabs/zed-python-api.git --branch zedsdk_3.X
